# application.yml

spring:
  profiles:
    active: dev
  application:
    name: www-service

server:
  error:
    whitelabel:
      enabled: false

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: http://email-service:8080
  company-service-endpoint: http://company-service:8080
  account-service-endpoint: http://account-service:8080
  recaptcha-public: ${RECAPTCHA_PUBLIC}
  recaptcha-private: ${RECAPTCHA_PRIVATE}